### PR TITLE
Fix: Error while setting up platform huesensor - KeyError: 'hue'

### PR DESCRIPTION
**Pull request by JurajNyiri**
Hello,

After upgrading to Home Assistant 0.94.x (or it also might have been hue bridge, which I updated at the same time) I started randomly encountering a new issue. Often after restart/start, huesensor would crash and not recover. This affected all domains, binary_sensor, device_tracker, and sensor.

```
Error while setting up platform huesensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/config/custom_components/huesensor/sensor.py", line 174, in async_setup_platform
    await data.async_update_info()
  File "/config/custom_components/huesensor/sensor.py", line 231, in async_update_info
    bridges = get_bridges(self.hass)
  File "/config/custom_components/huesensor/sensor.py", line 153, in get_bridges
    for entry in hass.data[hue.DOMAIN].values()
KeyError: 'hue'
```

The code provided should fix the issue, tested with restarts multiple times.

### CODE REVIEW

**Comment by robmarkcole** [comment]
Thanks for raising this, will request @yottatsa to comment

**Comment by JurajNyiri** [comment]
Thank you @robmarkcole . 
I have also pushed just now update to the version for custom_updater so that users get notified about the update.
Please feel free to adjust/cherry-pick as necessary.

**Comment by JurajNyiri** [comment]
Just tested this on my backup HASS still running on 0.93.x and it also crashed there, so it seems related to not HASS update but to Hue update. I guess people will start seeing this more and more as they update the hue bridge.

**Comment by JurajNyiri** [comment]
Hello, any update on merging this? It has been confirmed to work by 2 users in community forums so far. 
I would like to be able to soon switch back to this repo using [HACS](https://github.com/custom-components/hacs/) for any other future updates.

**Comment by robmarkcole** [comment]
@JurajNyiri can you confirm whether you have `hue:` in your configuration.yaml? 
BTW I have the same bridge firmware as you but do not get the issue reported.
Thanks

**Comment by JurajNyiri** [comment]
@robmarkcole yes I do
```
hue:
  bridges:
    - host: 192.168.100.7
```

I think it might depend on the order in which the components are loaded? Maybe in some cases, this component loads sooner than hue so hue is not yet available(?). If that would be true, it might be also affected by other components used, overall setup and HW on which HASS is running. Or maybe even Philips bridge setup/number of sensors etc., maybe it responds later in some cases so hue is not ready yet? I did not investigate too deeply, I saw it was happening intermittently every other launch or so, so I just added a check to see if the hue is available in the object and if not, try again in a while.

**Comment by robmarkcole** [comment]
Tbh I see all kinds of errors from the hue hub, clearly its quite complicated and also a moving target. Lets park this PR until we have a solid handle on the issue

**Comment by robmarkcole** [comment]
Hi
I can't find the original issue? If there is not one can you please create one.
Thanks

**Comment by JurajNyiri** [comment]
No issue has been created on github yet, I created a new one [here](https://github.com/robmarkcole/Hue-sensors-HASS/issues/152).

**Comment by yottatsa** [comment]
Could you please rebase, remove version bump, and [blackify](https://github.com/python/black)? It seems like a dependency issue for me, and I've tried to set a dependency in #154, but a safety check doesn't hurt. Thank you for adding it.

**Comment by robmarkcole** [comment]
This is stale now

**Pull request closed without merging**
