### PR TITLE
Add heavy-duty CI and format

### PR DESCRIPTION
**Pull request by KTibow**
This adds GitHub Actions.

### CODE REVIEW

**Comment by robmarkcole** [comment]
@KTibow nice one. Does appear black changed the formatting for some reason?
RE actions these are new to me, could you add a small section to the readme Developers section, explaining what the actions acomplish?

**Comment by KTibow** [comment]
Looks like that's another legacy PR that I made. Sure, I'll add that, while I migrate this to ha-blueprint.

**Comment by robmarkcole** [comment]
LGTM!

**Comment by robmarkcole** [comment]
@KTibow you comment on this error? https://travis-ci.org/github/robmarkcole/Hue-sensors-HASS
Thanks

**Comment by KTibow** [comment]
GitHub Actions is separate from Travis CI. I believe that this isn't related, and not my fault. As [you can see](https://github.com/robmarkcole/Hue-sensors-HASS/actions) GitHub Actions works just fine.

**Comment by robmarkcole** [comment]
NP, GitHub Actions are new to me, so I've disabled travis on this repo now

**Comment by robmarkcole** [comment]
@KTibow is it straightforward to run pytest with an action also?

**Comment by KTibow** [comment]
Sure, just add something like this:
- run: |
    pip install pytest
    pytest

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request merged**
