### PR TITLE
Add Friends of Hue switch support

### PR DESCRIPTION
**Pull request by claytonjn**
Based on the work of @elmigbot in #95

### CODE REVIEW

**Comment by robmarkcole** [comment]
Excellent!

**Comment by robmarkcole** [comment]
Thanks to @claytonjn for adding support for [Friends of Hue switches](https://www2.meethue.com/en-gb/friends-of-hue/switches)

**Comment by warcanoid** [comment]
@romarkcole can you add-implement friend of lights: https://github.com/home-assistant/home-assistant/issues/20638, last post from @dynamiik, to stop lights from flickering time to time

**Comment by robmarkcole** [comment]
@warcanoid please create a feature request, rather than commenting on a merged PR. Thanks

**Comment by warcanoid** [comment]
ok, thank you!

**Pull request merged**
