### PR TITLE
Fix 213

### PR DESCRIPTION
**Pull request by robmarkcole**
Fix https://github.com/robmarkcole/Hue-sensors-HASS/issues/213

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
HI Rob, 

just to let you know, and ask if/how this could be possible:

after this fix, deleting the dependencies from all files, my HA instance has calmed down enormously and the constant unavailability of the Hue lights has diminished a great deal...
This unavailability has been a thing pestering a lot of people a long time, and without the various iterations of HA hue integration and this CC been more prominent a times. It was 'solved' (for me) when we were at 104.3 HA.

Then updating to 105 it came back in all its frustrating intensity. This might have been coinciding with the updates and splitting up in the HUE CC repo here.

Now you've updated the __init__.py and streamlined the others, and as said, especially taking out 
```
 DEPENDENCIES = ["hue"]
```

HA responds much better.
There's still a few errors around in the logs about fetching data, but they are supposed to be solved in 106.

Did the  `DEPENDENCIES = ["hue"]` have such impact? It almost feels like another HA instance altogether.

Would be interested in your view on this.
Keep on streamlining the CC, it makes a world of difference!
Thanks.

**Comment by robmarkcole** [comment]
`DEPENDENCIES = ["hue"]` was actually doing nothing, as the dependencies are defined in `manifest.json`

**Comment by Mariusthvdb** [comment]
hmm, that's odd. Just did a config check, which took ages since mentioned updates, and it was swift as before, after the fix you did.

either that, or the update to supervisor 200 made the difference. Nothing else changed on this side.

**Comment by robmarkcole** [comment]
its a mystery :)

**Pull request merged**
