### PR TITLE
Version 1.0.3

### PR DESCRIPTION
**Pull request by yottatsa**
* `binary_sensor.hue` for motion sensor
* exponential backoff removed for faster initialisation

Closes: #103, #54

### CODE REVIEW

**Comment by robmarkcole** [comment]
Great!

**Comment by Mariusthvdb** [comment]
please allow 2 questions:

- is this the motion sensor detecting motion (on), detected, and no motion (off) , now seen as clear? or is it the sensor being on, as in in detecting mode.

- secondly, I hope we can override the icon and icon_color? Since this is an alert icon, I have it customized to red in my current setup, and distinguish it from a regular sensor being 'on' and having the yellow color as referenced above. Also, the proposed icon is fine, but it should be possible to set other mdi:icons. I have 11 of these sensors, and for easy glancing sake, use different icons to set them apart in the frontend...

Might be an edge case (though I don't think so....) but hope you'd consider this, and see if my request is possible?
thanks for that!

**Comment by Mariusthvdb** [comment]
maybe I missed something, but just updated to the version 1.0.3 of the sensor (not yet binary_sensor) and all of my sensors are gone... Are the previously created sensor now gone and need we to use different sensors? Or is this a bug....

**Comment by yottatsa** [comment]
`binary_sensor` has only two states: `Detected` whenever motion is detected and `Clear` when is no motion. Icon, text, and colours are the same for all motion binary sensors across Hass. There is atleast [one thread about customisations](https://community.home-assistant.io/t/need-help-with-sensor-icon-color-based-on-state/49292/15)

You still need `sensor/hue.py` if you use remotes. I would like to convert them to actual remotes, but I don't have any.

**Comment by Mariusthvdb** [comment]
I understand meanwhile... You might want to warn users for the enormous breaking change here, it is rather a paradigm shift you've implemented. 

Not only need we now 3 CC's where 1 sufficed previously, (might still want to think about naming them differently to distinguish them from one another), having to template the attributes out of a binary_sensor seems awkward. It is as you say yourself: a binary_sensor has only 2 states. 

And not 6 extra attributes, needed for what should be the true sensors. 
But, maybe you'll change that in the next iteration?

the thread about customizations isn't unfamiliar to me... 

about the remotes, I use them all, so if I can assist in the conversion, just let me know.

**Pull request merged**
