### PR TITLE
Update remote.py

### PR DESCRIPTION
**Pull request by barisahmet**
Lutron aurora button press doesn't update `last_updated`.

### CODE REVIEW

**Comment by robmarkcole** [comment]
Could you also add a test for `parse_z3_switch`?
Much appreciated

**Comment by barisahmet** [comment]
@robmarkcole Sorry, but I don't know how to do that. But I can provide json response if that helps.

**Comment by robmarkcole** [comment]
Yes please post it here, I will have to add the test then

**Comment by robmarkcole** [comment]
@barisahmet are you still working on this?

**Pull request closed without merging**
